# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
# This is a sample for a Secret which can be referenced from an
# InnoDBCluster manifest to create a "root" user for your use.
# The operator will in addition create other users.
#
# Please edit the file with values you like before deploying.
#
apiVersion: v1
kind: Secret
metadata:
  name: mypwds
stringData:
  rootUser: replace me with a username like root
  rootHost: '%'
  rootPassword: set me to a password
